### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [AMevans12/Quantum-Codes-Qiskit-Module-#1]
I recently came across your project Quantum-Codes-Qiskit-Module- and I noticed that the repository github.com/AMevans12/Quantum-Codes-Qiskit-Module- currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by AMevans12** [comment]
Hi Juan,

Thank you for bringing this to my attention! I've gone ahead and added the
Apache 2.0 license to the Quantum-Codes-Qiskit-Module
<https://github.com/AMevans12/Quantum-Codes-Qiskit-Module-> repository. I
appreciate your suggestion, and I hope this helps make the project more
accessible for everyone in the community.

If you have any other feedback or suggestions, feel free to let me know.
Your contributions will be much appreciated. Thanks again for your support!

Best regards,

**Comment by cbjuan** [comment]
Thank you!
